[package]
name = "softladder-io"
description = "I/O image, driver trait and simulation driver for SoftLadder"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
softladder-core = { path = "../softladder-core" }
thiserror = { workspace = true }
